[project]
name = "mcp-and-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-identity>=1.25.0",
    "arize-phoenix-otel>=0.16.0",
    "fastapi>=0.141.1",
    "fastmcp>=4.0.3",
    "langchain[mcp]>=1.4.0",
    "langchain-azure-ai>=1.2.3",
    "langgraph>=1.2.11",
    "langchain-openai>=1.6.2",
    "openai>=3.13.0",
    "openinference-instrumentation-langchain>=0.1.67",
    "openinference-instrumentation-openai>=0.1.60",
    "opentelemetry-instrumentation-fastapi>=0.65b0",
    "pydantic-settings>=2.15.0",
    "uvicorn>=0.53.0",
    "openai-agents>=0.3.0",
    "openinference-instrumentation-openai-agents>=2.4.1",
]

[dependency-groups]
dev = [
    "ruff>=0.16.7",
]
