[project]
name = "mcp-and-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-identity>=1.25.0",
    "fastapi>=0.141.1",
    "fastmcp>=4.0.3",
    "openai>=3.13.0",
    "pydantic-settings>=2.15.0",
    "uvicorn>=0.52.4",
]

[dependency-groups]
dev = [
    "ruff>=0.16.7",
]
